version: '3'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx-docker
    ports:
      - 8080:80
      - 3000:3000
      #- 33112:33110
      # - 9999:9999
    # restart: always
    volumes:
      - "/Users/yilin9999/project/big-ben/run/uwsgi.sock:/run/uwsgi.sock"
      #- "./../../big-ben/uwsgi.sock:/run/uwsgi.sock"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./letsencrypt:/etc/letsencrypt"
      - "./html:/usr/share/nginx/html"
      # - "./var/log/nginx:/var/log/nginx"
